//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gamboo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise
    {
        public int eID { get; set; }
        public string eName { get; set; }
        public string eSubstance { get; set; }
        public System.DateTime eTime { get; set; }
        public int mID { get; set; }
    
        public virtual Manager Manager { get; set; }
    }
}
