//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gamboo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameRole
    {
        public int rID { get; set; }
        public string rName { get; set; }
        public Nullable<int> occupation { get; set; }
        public Nullable<int> camp { get; set; }
        public string passive { get; set; }
        public string Initiative { get; set; }
        public string acquire { get; set; }
        public string img { get; set; }
    }
}
