//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gamboo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int vID { get; set; }
        public int uID { get; set; }
        public string src { get; set; }
        public string vTitle { get; set; }
        public Nullable<System.DateTime> vTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
